name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom-staging[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test
        setup-command: ''
        command: echo "Hello World!"
        input: ''
        expected-output: Hello World!
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Python test
      id: python-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 100
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
        PYTHON-TEST_RESULTS: "${{steps.python-test.outputs.result}}"
      with:
        runners: test,python-test
